node.js: File Index
node::FSReqWrap Class Reference
Public Member Functions
void * operator new (size_t size)
void * operator new (size_t size, char *storage)
FSReqWrap (Environment *env, Local< Object > req, const char *syscall, char *data=NULL)
void ReleaseEarly ()
const char * syscall () const
const char * dest () const
unsigned int dest_len () const
void dest_len (unsigned int dest_len)
Public Member Functions inherited from node::ReqWrap< uv_fs_t >
ReqWrap (Environment *env, v8::Handle< v8::Object > object, AsyncWrap::ProviderType provider)
~ReqWrap ()
void Dispatched ()
Public Member Functions inherited from node::AsyncWrap
AsyncWrap (Environment *env, v8::Handle< v8::Object > object, ProviderType provider, AsyncWrap *parent=NULL)
~AsyncWrap ()
uint32_t provider_type () const
v8::Handle< v8::Value > MakeCallback (const v8::Handle< v8::Function > cb, int argc, v8::Handle< v8::Value > *argv)
v8::Handle< v8::Value > MakeCallback (const v8::Handle< v8::String > symbol, int argc, v8::Handle< v8::Value > *argv)
v8::Handle< v8::Value > MakeCallback (uint32_t index, int argc, v8::Handle< v8::Value > *argv)
Public Member Functions inherited from node::BaseObject
BaseObject (Environment *env, v8::Local< v8::Object > handle)
~BaseObject ()
v8::Local< v8::Object > object ()
v8::Persistent< v8::Object > & persistent ()
Environment * env () const
template<typename Type >
void MakeWeak (Type *ptr)
void ClearWeak ()
Additional Inherited Members
Public Types inherited from node::AsyncWrap
enum ProviderType
Public Attributes inherited from node::ReqWrap< uv_fs_t >
QUEUE req_wrap_queue_
uv_fs_t req_
Detailed Description
Definition at line 69 of file node_file.cc.
Constructor & Destructor Documentation
node::FSReqWrap::FSReqWrap (Environment * env, Local< Object > req, const char * syscall, char * data = NULL) inline
Definition at line 74 of file node_file.cc.
References node::Wrap().
    : ReqWrap<uv_fs_t>(env, req, AsyncWrap::PROVIDER_FSREQWRAP),
      syscall_(syscall),
      data_(data),
      dest_len_(0) {
    Wrap(object(), this);
  }
Member Function Documentation
const char* node::FSReqWrap::dest () const inline
Definition at line 93 of file node_file.cc.
{ return dest_; }
unsigned int node::FSReqWrap::dest_len () const inline
Definition at line 94 of file node_file.cc.
{ return dest_len_; }
void node::FSReqWrap::dest_len (unsigned int dest_len) inline
Definition at line 95 of file node_file.cc.
References dest_len().
Referenced by dest_len().
{ dest_len_ = dest_len; }
void* node::FSReqWrap::operator new (size_t size) inline
Definition at line 71 of file node_file.cc.
{ return new char[size]; }
void* node::FSReqWrap::operator new (size_t size, char * storage) inline
Definition at line 72 of file node_file.cc.
{ return storage; }
void node::FSReqWrap::ReleaseEarly () inline
Definition at line 85 of file node_file.cc.
                      {
    if (data_ == NULL)
      return;
    delete[] data_;
    data_ = NULL;
  }
const char* node::FSReqWrap::syscall () const inline
Definition at line 92 of file node_file.cc.
{ return syscall_; }
The documentation for this class was generated from the following file:
src/node_file.cc
node.js documentation generated at Sun Oct 4 2015 01:05:20
Please contact me if something went wrong of it you would like to see an other project in docs.
docs uses jenkins and doxygen.